<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>图片版本第一行数据</name>
   <tag></tag>
   <elementGuidId>a8165b47-9b99-45f5-8e49-ed2afb3e976b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/section/section/main/div/div[3]/div/div[2]/div/div[2]/div/div/div/div/div[1]/div[2]/table/tbody/tr/td[8]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>table/tbody/tr/td[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>table/tbody/tr/td[8]</value>
   </webElementProperties>
</WebElementEntity>
