<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>通讯底层版本第一行数据</name>
   <tag></tag>
   <elementGuidId>54a42f64-99f6-461c-af48-892c1522f99a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div/div[2]/section/section/main/div/div[3]/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/table/tbody/tr/td[10]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>table/tbody/tr/td[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>table/tbody/tr/td[10]</value>
   </webElementProperties>
</WebElementEntity>
