<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>变更管理增删改查</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3a16ba49-5bd8-4acb-904a-e7a334e22d76</testSuiteGuid>
   <testCaseLink>
      <guid>cf5dac89-3cf7-4190-adbd-444a9cf93d1b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/批量导入功能/ZSXT-1969批量导入功能测试-步骤6有已知问题</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0ec3f17-d331-437d-8ac3-cc9c77e3279c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94d76178-5bf8-44fd-bea9-60538eb87043</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/删除功能/ZSXT-1737点击每页的全选按钮,选中当前页的所有记录,删除成功</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e852fec9-4713-4bc5-a399-85950558226c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/删除功能/ZSXT-1821选择需要删除的记录,删除成功</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7bb43eaa-a8b4-4d30-abae-8898eb82ed80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/删除功能/ZSXT-1885不选择任何记录,直接点击删除按钮,提示需要选择删除的记录</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f7e2bc69-a14f-478c-a20f-150a4d14e6ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/批量导入模板下载功能/ZSXT-1955批量导入模板下载功能测试</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>361fdbbe-3f90-4adc-84bd-0fdccc002dc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/批量导入模板下载功能/ZSXT-3101批量导入模板字段位置检查</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>221242ec-957d-4126-b8fe-a90ca6ef934a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/导出功能/ZSXT-1937导出1条记录</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1f2f700e-f389-4537-957f-5307583dc47f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/导出功能/ZSXT-2010搜索出需要导出的记录,点击导出按钮,可以成功导出对应的记录</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e214b625-bca4-43c5-a0d6-0c2c918334e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/导出功能/ZSXT-1743导出16条记录</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>59385eac-d903-40ce-9ab8-ee3340bdbe4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-1873翻页按钮功能测试</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>faf4c79e-b50b-4115-b10e-3880fead7944</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-2215产品型号查询测试</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b8363e32-7c93-4909-9184-f976f9ddc3cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-2218变更人查询测试</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bdf2eebd-011e-46e5-9304-dee4e52db616</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-2222类别查询测试</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f877d8c-b9a5-460b-94b0-da875c510359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8246cfc0-36f3-49bb-9b16-a08aa4272fcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa79c7c2-a91a-4798-a8aa-fb7e20e4b2cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f860e9cd-bbcd-49ed-823e-2dc6c06d4cb7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5de40a5-2019-4fe4-b143-5c583557f418</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>809074fc-fdc3-4b16-b6c3-024b8eef05f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33abf08b-252e-44fc-982a-ff11b190a8b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28b2e402-6c87-4d28-af84-abf79809e3fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5cf3875-8305-4b9f-996c-fd5bc92901d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>793c70e7-9c32-4183-b41e-c77c43cb46b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31cd4931-2e25-4388-9464-e4f2bf4c5031</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-2247是否试装查询测试</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10ef26f7-adea-40a3-a524-468e0b53aa52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39010801-5ccd-418e-8bc5-70ec6247413d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2702c59-924c-4b24-9f12-e620e7fcea8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-2258状态查询测试</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcd92142-5174-4a09-92ad-162287d4c485</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e99eb92-ebb2-47df-bc7d-c30b2ce6769b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae517e20-aef0-4942-bfa7-15364be6e629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f4a7aee-4fbc-4161-a30b-c3149092e621</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80cc51f1-3659-4429-b8a2-4825a380c212</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ac79b75-5f11-41e7-a6f3-317ecd3e08ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81bd3632-ca28-4249-84ff-2c4fb3376078</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3900238e-f6dc-4af4-8a98-bbf9ae769181</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-2259评审时间查询测试</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06af86bf-8993-482f-9065-a976051982c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5766ebb-4e54-4798-9744-17b3be3b3888</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4b71365-f51f-4f5b-910c-f7ff6f7b1131</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-2260不选择任何字段,直接点击查询按钮</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>02101aae-14b8-45b7-8066-9f01841d9382</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-2272变更编码查询测试</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a83c7d32-8b94-4446-ae3f-d3682194415e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/查询及列表功能/ZSXT-3220变更管理--增加搜索框物料编码,主体编码</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b3d9972-8176-44dc-aa68-dec1fb7c0101</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec7e4f50-d55f-474f-b8e0-635b79049aed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66323ab5-1775-4082-9e3d-367d7257cced</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3539f148-8a7b-41e6-97d0-51f9cc582ca2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6a6f8b9-cf14-4922-8258-65822c829d9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9ceb0e2-5215-4578-a0d9-f8612b11b738</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8bbde1ed-4673-4f66-92fe-eb9b198cef57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/清除功能/ZSXT-1755直接点击清除按钮,清除成功</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>05e4026e-fb17-4fc6-a563-4bee5169b044</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/清除功能/ZSXT-1967查询列输入所有信息,点击清除按钮,清除成功</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>048ea950-51c2-4ae3-aebe-b7a79c5dc59b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69a786c7-ac8a-434d-91d6-1bb048ef05c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04bf1cba-00c2-4d86-b2b3-4353b466d2cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/编辑功能/ZSXT-2220产品型号,物料编码,主题编码可以多行输入</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e49212c-0a33-4247-8e59-ad5fa67ade7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f671d202-c1a5-4df4-b8ea-c31443e6e380</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b103f419-3bff-48da-bf31-e20fefb04423</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7356fdb4-0152-408f-b8fa-b5d4a105ebf3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/编辑功能/ZSXT-2547根据变更编码查询数据是否存在,如果存在直接返回,提示用户数据已存在</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6e0e872-6a26-4946-a524-618818841b93</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc9a4773-4229-4638-9d48-a95e1071f044</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/编辑功能/ZSXT-2550变更编码不能修改为空</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9ac56cfa-baf9-4aa8-9006-45740064b8e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/编辑功能/ZSXT-2556修改可以为空的字段修改成功</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7a56eaf7-51e3-43cb-a67e-3c4ad9c556cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/编辑功能/ZSXT-2557如果状态为完成,评审时间必须存在</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>005b0eec-ddfd-4ca3-a91d-1b2a22af749a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/控制台/ZSXT-2546变更信息显示正确</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>121b7afe-f0ba-4f7d-a612-be76652369f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/控制台/ZSXT-2561测试信息显示正确</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4f24bed0-0723-43bf-b565-d44211fb6c56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/控制台/ZSXT-2544试装信息显示正确</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a020474-8bc3-471e-8cb6-ea046277c15d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef1ac892-fd16-47cc-a9de-c5d62ee17dfc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/追溯系统-项目管理/变更管理/删除功能/ZSXT-1753删除的数据保存在回收站里面</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
